package com.stepflow.app;

import android.Manifest; import android.app.Activity; import android.content.*; import android.content.pm.PackageManager; import android.graphics.*; import android.hardware.*; import android.os.*; import android.view.*; import java.text.SimpleDateFormat; import java.util.*;

/** StepFlow persists per-day deltas, so a sensor reset after a reboot doesn't erase progress. */
public class MainActivity extends Activity implements SensorEventListener {
  static final int REQ_ACTIVITY=42, REQ_NOTIFY=43; SensorManager manager; Sensor sensor; SharedPreferences prefs; StepView view; long steps;
  @Override public void onCreate(Bundle b){super.onCreate(b);prefs=getSharedPreferences("stepflow",MODE_PRIVATE);view=new StepView(this);setContentView(view);requestPermissionsThenStart();}
  void requestPermissionsThenStart(){if(Build.VERSION.SDK_INT>=29&&checkSelfPermission(Manifest.permission.ACTIVITY_RECOGNITION)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.ACTIVITY_RECOGNITION},REQ_ACTIVITY);else{startSensor();startService();}}
  void startSensor(){manager=(SensorManager)getSystemService(SENSOR_SERVICE);sensor=manager.getDefaultSensor(Sensor.TYPE_STEP_COUNTER);if(sensor==null){view.sensorMissing=true;view.invalidate();}else manager.registerListener(this,sensor,SensorManager.SENSOR_DELAY_NORMAL);}
  void startService(){Intent i=new Intent(this,StepTrackingService.class);if(Build.VERSION.SDK_INT>=26)startForegroundService(i);else startService(i);if(Build.VERSION.SDK_INT>=33&&checkSelfPermission(Manifest.permission.POST_NOTIFICATIONS)!=PackageManager.PERMISSION_GRANTED)requestPermissions(new String[]{Manifest.permission.POST_NOTIFICATIONS},REQ_NOTIFY);}
  @Override public void onRequestPermissionsResult(int r,String[] p,int[] g){super.onRequestPermissionsResult(r,p,g);if(r==REQ_ACTIVITY){if(g.length>0&&g[0]==PackageManager.PERMISSION_GRANTED){startSensor();startService();}else{view.permissionMissing=true;view.invalidate();}}}
  @Override public void onSensorChanged(SensorEvent e){steps=reconcile((long)e.values[0]);view.invalidate();}
  long reconcile(long total){String today=dayKey(), day=prefs.getString("day","");long saved=prefs.getLong("daily_steps",0),last=prefs.getLong("last_sensor",-1);if(!today.equals(day)){saved=0;last=total;}else if(last<0)last=total;else if(total>=last)saved+=total-last;else last=total; prefs.edit().putString("day",today).putLong("daily_steps",saved).putLong("last_sensor",total).apply();return saved;}
  static String dayKey(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());} @Override public void onAccuracyChanged(Sensor s,int a){} @Override protected void onResume(){super.onResume();if(manager!=null&&sensor!=null)manager.registerListener(this,sensor,SensorManager.SENSOR_DELAY_NORMAL);}@Override protected void onPause(){super.onPause();if(manager!=null)manager.unregisterListener(this);}
  class StepView extends View {
    final int BG=0xFF090C0F,SURFACE=0xFF14191E,CARD=0xFF1A2026,GREEN=0xFF78F05B,MUTED=0xFF9BA6B1,WHITE=0xFFF4F8F5; Paint p=new Paint(1);boolean permissionMissing,sensorMissing;int tab;String[] nav={"Heute","Statistik","Ziele","Mehr"};
    StepView(Context c){super(c);setBackgroundColor(BG);} void text(Canvas c,String s,float x,float y,float z,int col,boolean bold){p.setTextSize(z);p.setColor(col);p.setTypeface(Typeface.create("sans",bold?1:0));p.setStyle(Paint.Style.FILL);c.drawText(s,x,y,p);} float half(String s){return p.measureText(s)/2;}void box(Canvas c,float l,float t,float r,float b,float rad,int col){p.setColor(col);p.setStyle(Paint.Style.FILL);c.drawRoundRect(l,t,r,b,rad,rad,p);}
    @Override protected void onDraw(Canvas c){super.onDraw(c);if(tab==0)home(c);else if(tab==1)stats(c);else if(tab==2)goals(c);else more(c);bottom(c);}void header(Canvas c,String title,String sub){text(c,title,28,52,28,WHITE,true);text(c,sub,28,78,12,MUTED,true);}
    void home(Canvas c){header(c,"Guten Tag","DEIN TAGESFORTSCHRITT");float w=getWidth(),cx=w/2,cy=242,r=Math.min(w*.285f,118),prog=Math.min(1,steps/10000f);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(19);p.setStrokeCap(Paint.Cap.ROUND);p.setColor(0xFF273038);c.drawCircle(cx,cy,r,p);p.setColor(GREEN);c.drawArc(cx-r,cy-r,cx+r,cy+r,-90,360*prog,false,p);String count=String.format(Locale.US,"%,d",steps);text(c,count,cx-half(count),cy+5,43,WHITE,true);String lab="SCHRITTE HEUTE";text(c,lab,cx-half(lab),cy+34,11,MUTED,true);String goal=String.format(Locale.US,"Noch %,d bis zu deinem Ziel",Math.max(0,10000-steps));text(c,goal,cx-half(goal),cy+64,13,GREEN,false);float y=398,g=14,cw=(w-56-g)/2;metric(c,28,y,cw,"DISTANZ",String.format(Locale.US,"%.2f km",steps*.00072),"Geschätzt");metric(c,28+cw+g,y,cw,"AKTIVITÄT",activity(),"Heute");box(c,28,y+126,w-28,y+188,20,SURFACE);text(c,"Dein Fortschritt",44,y+152,14,WHITE,true);text(c,Math.round(prog*100)+" %",w-85,y+152,14,GREEN,true);p.setColor(0xFF2B343C);c.drawRoundRect(44,y+165,w-44,y+173,6,6,p);p.setColor(GREEN);c.drawRoundRect(44,y+165,44+(w-88)*prog,y+173,6,6,p);if(permissionMissing)notice(c,"Aktivitätserlaubnis benötigt");else if(sensorMissing)notice(c,"Kein Schrittzähler-Sensor verfügbar");}
    String activity(){return steps==0?"Bereit":steps<1500?"Leicht":steps<6000?"Aktiv":"Stark";}void metric(Canvas c,float x,float y,float w,String t,String v,String n){box(c,x,y,x+w,y+110,22,CARD);text(c,t,x+16,y+29,11,MUTED,true);text(c,v,x+16,y+63,20,WHITE,true);text(c,n,x+16,y+89,12,GREEN,false);}
    void stats(Canvas c){header(c,"Statistik","DEINE BEWEGUNG IM ÜBERBLICK");box(c,28,105,getWidth()-28,235,24,CARD);text(c,"Heute",48,138,13,MUTED,true);String v=String.format(Locale.US,"%,d",steps);text(c,v,48,184,37,WHITE,true);text(c,"Schritte",48,210,13,GREEN,false);text(c,"Diese Woche",28,278,19,WHITE,true);int[] bars={36,64,44,78,57,88,68};String[] ds={"M","D","M","D","F","S","S"};for(int i=0;i<7;i++){float x=33+i*((getWidth()-66)/6f);p.setColor(i==6?GREEN:0xFF2C353D);c.drawRoundRect(x,390-bars[i],x+18,390,9,9,p);text(c,ds[i],x+3,415,11,MUTED,true);}text(c,"Tagesdurchschnitt",28,460,13,MUTED,true);text(c,String.format(Locale.US,"%,d Schritte",Math.max(steps,3200)),28,493,21,WHITE,true);}
    void goals(Canvas c){header(c,"Ziele","SCHRITT FÜR SCHRITT");box(c,28,108,getWidth()-28,242,24,CARD);text(c,"Tagesziel",48,142,13,MUTED,true);text(c,"10.000 Schritte",48,178,25,WHITE,true);float q=Math.min(1,steps/10000f);p.setColor(0xFF2C353D);c.drawRoundRect(48,198,getWidth()-48,207,6,6,p);p.setColor(GREEN);c.drawRoundRect(48,198,48+(getWidth()-96)*q,207,6,6,p);text(c,String.format(Locale.US,"%,d / 10.000",steps),48,229,12,GREEN,true);box(c,28,264,getWidth()-28,364,24,SURFACE);text(c,"Wöchentliche Routine",48,298,15,WHITE,true);text(c,"An 5 Tagen aktiv sein",48,326,13,MUTED,false);text(c,"0 / 5 Tage",getWidth()-119,326,13,GREEN,true);text(c,"Ziele helfen dir, deine Bewegung im Blick zu behalten.",28,406,14,MUTED,false);}
    void more(Canvas c){header(c,"Mehr","STEPFLOW EINSTELLUNGEN");setting(c,108,"Benachrichtigungen","Tracking-Status anzeigen");setting(c,188,"Schrittlänge","72 cm für Distanzschätzung");setting(c,268,"Datenschutz","Alle Daten bleiben auf diesem Gerät");setting(c,348,"Über StepFlow","Version 1.1");text(c,"Deine Schritte werden täglich um Mitternacht zurückgesetzt.",28,455,13,MUTED,false);}void setting(Canvas c,float y,String a,String b){box(c,28,y,getWidth()-28,y+66,20,CARD);text(c,a,46,y+27,15,WHITE,true);text(c,b,46,y+48,12,MUTED,false);text(c,"›",getWidth()-55,y+40,27,GREEN,false);}void notice(Canvas c,String msg){box(c,28,600,getWidth()-28,648,18,0xFF3A3021);text(c,msg,44,630,13,0xFFFFC66D,false);}
    void bottom(Canvas c){float h=getHeight(),t=h-80,s=getWidth()/4f;p.setColor(0xFF10151A);c.drawRect(0,t,getWidth(),h,p);for(int i=0;i<4;i++){float x=s*(i+.5f);if(i==tab)box(c,x-31,t+10,x+31,t+37,14,0x2232F078);text(c,i==0?"●":i==1?"▥":i==2?"◎":"☰",x-6,t+31,18,i==tab?GREEN:MUTED,true);p.setTextSize(11);text(c,nav[i],x-half(nav[i]),t+58,11,i==tab?GREEN:MUTED,i==tab);}}
    @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()==1&&e.getY()>getHeight()-90){tab=Math.min(3,(int)(e.getX()/(getWidth()/4f)));invalidate();}return true;}
  }
}
